### ISSUE TITLE
Comment does not mathe the code

### ISSUE THREAD

**Issue by meng-wenlong** [YuchuanTian/AIGC_text_detector#5]
Hi! Thank you for open-sourcing the code. I find a typo in train.py. The comments in line 99 and line 101 do not match the code. The code select short human sentences, while the comment says it select long sentences. After reading the paper, I think the code is right. I hope the owner revises this mistake since it is confusing. I have launched a pull request #6 to revise this mistake.

**Comment by YuchuanTian** [comment]
We apologize that the naming and comments could cause misunderstanding. Your pull request is approved. Thanks for your advice!
