### ISSUE TITLE
The effect of batch size & pretrained weight for validation in the paper

### ISSUE THREAD

**Issue by qiyue-hub** [YuchuanTian/AIGC_text_detector#7]
Thank you for this wonderful work!
However, we encounter several problems during reproduction.
I run the code using Roberta on dataset HC3, while I get a result of all predictions to be negative.
The only difference with the provided tutorial is that, I adjust the batch size from 32 to 4 due to limited GPU memory.
I wonder whether batch size influences the result that severely.
![image](https://github.com/YuchuanTian/AIGC_text_detector/assets/52554947/6e7b8da1-a8a2-43cf-861f-37701b05a9a8)
Also, I would be appreciated if the pretrained weights used in the paper can be updated. In that case, I can skip the problem of limitation of GPU. 
Thanks!

**Comment by YuchuanTian** [comment]
It is shocking to me that the reduction of training batchsize could yield a detector that completely fails. A probable reason is the significantly-increased iteration, which brings about overfitting.

We will release the checkpoints in a handful of days for your convenience. Please keep tuned, and thank you!

**Comment by qiyue-hub** [comment]
Thanks for your response! We adjust the batchsize and do get the results as reported in the paper!
The results on the HC3-sent dataset are promising. Looking forward to following works.
